language: ruby
sudo: false
cache: bundler

branches:
  only: master

services:
  - redis-server

rvm:
  - 2.4
  - 2.5

gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile

matrix:
  exclude:
    # Rails 4.2
    - rvm: 2.5
      gemfile: gemfiles/rails4.2.gemfile
    # Rails 5.0
    - rvm: 2.5
      gemfile: gemfiles/rails5.0.gemfile

before_install: rm Gemfile.lock gemfiles/*.lock
script: bundle exec rake test
